import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import Header from "@/components/Header";
import Seo from "@/components/Seo";
import MobileNav from "@/components/MobileNav";

const sections = [
  {
    title: "1. What this service is",
    body: "AfuChat Movies is a free movie and television discovery library. It provides information about titles and links to third-party services that may carry them. It does not host, stream, download or otherwise distribute any video content.",
  },
  {
    title: "2. Accounts",
    body: "An account is optional and only needed to save titles to My List and keep a recently viewed list. You are responsible for keeping your sign-in credentials secure and for activity carried out under your account. You may stop using the service and request deletion at any time.",
  },
  {
    title: "3. Acceptable use",
    body: "Do not scrape the service at volume, attempt to bypass rate limits or security controls, or use it to distribute unlawful material. We may suspend access that harms the service or other users.",
  },
  {
    title: "4. Third-party content and links",
    body: "Catalogue data, artwork and reviews are provided by The Movie Database (TMDB) and remain the property of their respective owners. Availability listings are indicative and can be inaccurate or out of date. Following an outbound link means the destination service's own terms and pricing apply.",
  },
  {
    title: "5. AI-generated content",
    body: "Recommendations, mood matches and insights are generated by Engagera AI and may be incomplete or wrong. Treat them as suggestions rather than facts, and verify anything important against the title's source data.",
  },
  {
    title: "6. Availability and changes",
    body: "The service is provided 'as is' without warranty of any kind. Features may change or be withdrawn, and we do not guarantee uninterrupted availability. To the extent permitted by law we are not liable for losses arising from use of the service.",
  },
  {
    title: "7. Contact",
    body: "Questions about these terms can be sent to support@afuchat.com.",
  },
];

const TermsPage = () => {
  return (
    <div className="min-h-screen bg-background pb-24 md:pb-10">
      <Seo
        title="Terms of Service — AfuChat Movies"
        description="The terms that apply when using the AfuChat Movies discovery library."
        path="/terms"
      />
      <Header />

      <main className="pt-28 md:pt-24">
        <div className="mx-auto w-full max-w-3xl px-4">
          <div className="flex items-center gap-3 py-4">
            <Link to="/settings" className="text-muted-foreground hover:text-foreground">
              <ArrowLeft className="h-5 w-5" />
            </Link>
            <h1 className="text-xl md:text-2xl font-bold">Terms of Service</h1>
          </div>
          <p className="text-xs text-muted-foreground mb-6">Last updated 11 August 2026</p>

          <div className="space-y-5">
            {sections.map((s) => (
              <section key={s.title} className="p-4 bg-card rounded-lg">
                <h2 className="text-sm font-semibold mb-1.5">{s.title}</h2>
                <p className="text-xs md:text-sm text-muted-foreground leading-relaxed">{s.body}</p>
              </section>
            ))}
          </div>
        </div>
      </main>

      <MobileNav />
    </div>
  );
};

export default TermsPage;
